---
title: "Homework#Week04#CI"
author: "Meng-Hsin, Wu"
date: "2022/3/12"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

First, we need to check the original datasets.
--------
```{r data checking, echo=F}
rm(list=ls())
setwd("~/Courses of 110 semester-2/Intensive Statistical Ecology/0303/mock_dataTS/mock_dataTS")
library(readxl)
FishCopData<-read_xls('enviANDdensity.xls')
FishCopDens<-FishCopData[11:12]
colnames(FishCopDens)<-c('Fish', 'Copepod')
FishDens<-FishCopDens$Fish
CopDens<-FishCopDens$Copepod
paste('Density of fish and copepod')
data.frame(Fish=FishDens, Copepod=CopDens)





```

Question_1: Computing coefficients
-----
Let's calculate slope and intercept between fish and copepods.
```{r coefficients, echo=FALSE}
######Call for my lm function#######
MylmCoefficient<-function(x,y){
  is.array(x)
  is.array(y)
  beta1_up<-sum((x-mean(x))*(y-mean(y)))
  beta1_down<-sum((x-mean(x))^2)
  beta1<-beta1_up/beta1_down
  beta0<-mean(y)-beta1*mean(x)
  
  return(c(beta1, beta0))
}
####################################
paste('Slope=', MylmCoefficient(CopDens, FishDens)[1])
paste('Intercept=', MylmCoefficient(CopDens, FishDens)[2])


```

Question_1: The 95% CI of beta 1
-----
Using percentile and bootstrapping
```{r percentile, echo=FALSE}

########Replace the function quantile###################

myPercentile<-function(x, prob){
  is.array(x)
  is.numeric(prob)
  x.sort<-sort(x)
  position<-length(x.sort)*prob
  if(is.integer(position)==TRUE){
    value<-(x.sort[position]+x.sort[position+1])/2
  }else if(is.integer(position)==FALSE){
    position1<-floor(position)
    value<-x.sort[position1]}
  return(value)
}
######Replace the function ecdf######
myECDF<-function(x, N){
  is.array(x)
  is.numeric(N)
  if(N>max(x)|N<min(x)){
    paste('Please do not do something silly')
  }else{
    x.sort<-sort(x)
    below<-length(x.sort[x.sort<=N])
    percentile<-below/length(x.sort)
    return(percentile)
  }
}
#####################################
######Bootstrapping##################

corr.coef<-c()
corr.interc<-c()
FishCopSelect<-list()
for(i in 1:999){
  
  rNumber<-ceiling(runif(34, min=0, max=34))
  FishCopSelect<-FishCopDens[rNumber,]
  corr.coef[i]<-MylmCoefficient(FishCopSelect$Copepod, FishCopSelect$Fish)[1]
  corr.interc[i]<-MylmCoefficient(FishCopSelect$Copepod, FishCopSelect$Fish)[2]
}
corr.coef[1000]<-MylmCoefficient(CopDens, FishDens)[1]
corr.interc[1000]<-MylmCoefficient(CopDens, FishDens)[2]
Beta1_Sort<-sort(corr.coef)

corr.CI<-myPercentile(Beta1_Sort, c(0.025, 0.975))

paste('The 95% CI falls between',
      corr.CI[1],
      'and',
      corr.CI[2]
      )



```


Question_1: The 95% CI of beta 1
-----
Using BC
```{r beta1 BC, echo=FALSE}
Beta1_origin<-mean(corr.coef)
#G(theta)
G_theta<-myECDF(Beta1_Sort, Beta1_origin)
#Gaussian-distributed array
Gauss<-rnorm(1000, mean=0, sd=1)
#Z0
Z0<-myPercentile(Gauss, G_theta)
Z0<-as.numeric(Z0)
Z1<-2*Z0-1.96
Z2<-2*Z0+1.96
G.sort<-sort(Gauss)
prob.return.1<-myECDF(G.sort, Z1)
prob.return.2<-myECDF(G.sort, Z2)
#Find the CI of BC method
BC.CI<-myPercentile(Beta1_Sort, c(prob.return.1, prob.return.2))

paste('The 95% CI falls between',
      BC.CI[1],
      'and',
      BC.CI[2]
      )

```

Question_1: The 95% CI of beta 1
-----
Using BCa
```{r Slope CI BCa, echo=FALSE}
################################
JKcorr<-array()
JKinterc<-c()
for(i in 1:34){
  JKcorrList<-FishCopDens[-i, ]
  JKcorr[i]<-MylmCoefficient(JKcorrList$Copepod,
                             JKcorrList$Fish)[1]
  JKinterc[i]<-MylmCoefficient(JKcorrList$Copepod,
                               JKcorrList$Fish)[2]
}
#############################################
####Compute a################
JKcorr.mean<-mean(JKcorr)
UpperPart<-sum((JKcorr.mean-JKcorr)^3)
LowerPart<-6*sum((JKcorr.mean-JKcorr)^2)^(3/2)
a.BCa<-UpperPart/LowerPart
G.theta.BCa<-myECDF(Beta1_Sort, Beta1_origin) #G(theta)
Z0.BCa<-myPercentile(Gauss, G.theta.BCa)
Z0.BCa<-as.numeric(Z0.BCa) 
#Standardize Z0
Z1.BCa<-Z0.BCa+(Z0.BCa-1.96)/(1-a.BCa*(Z0.BCa-1.96))
Z2.BCa<-Z0.BCa+(Z0.BCa+1.96)/(1-a.BCa*(Z0.BCa+1.96))
#Check the position of standardized CL
Prob.BCa.1<-myECDF(G.sort, Z1.BCa)
Prob.BCa.2<-myECDF(G.sort, Z2.BCa)
# Re-project the position back to the bootstrapped cdf
myPercentile(Beta1_Sort, c(Prob.BCa.1, Prob.BCa.2))
# Re-project the position back to the bootstrapped cdf
BCa.CI<-myPercentile(Beta1_Sort, c(Prob.BCa.1, Prob.BCa.2))
paste('The 95% CI falls between',
      BCa.CI[1],
      'and',
      BCa.CI[2]
      )


```
Make comparison between three methods
-------
```{r comparison, echo=FALSE}
data.frame(Percentile_CI=corr.CI,
           BC_CI=BC.CI,
           BCa_CI=BCa.CI)

paste('0 is not included in these CIs, the coefficient is  significantly different from 0')
```
Before Question_2, check the species data
------
The density of O.venusta and C.pauper.
```{r import SP data, echo=FALSE, warning=FALSE, message=FALSE}
setwd("~/Courses of 110 semester-2/Intensive Statistical Ecology/0303/mock_dataTS/mock_dataTS")
CopData<-read_xls('copepod_datasheet.xls',
                  col_names =T)
CopData<-t(CopData)
CopData<-as.data.frame(CopData)
row.names(CopData)<-CopData$V1
CopData<-CopData[-1,]
colnames(CopData)<-CopData[1,]
CopData<-CopData[-1,]

#Confirm that all data in this data frame are characters
CopSPData<-sapply(CopData[2:182], FUN=as.numeric)
CopSPDensity<-CopSPData*CopDens #Get the species density

CopSPDensity<-as.data.frame(CopSPDensity)
OVdensity<-CopSPDensity$`Oncaea venusta`
CPdensity<-CopSPDensity$`Canthocalanus pauper`
OVCP<-cbind(OV=OVdensity, CP=CPdensity)
OVCP<-as.data.frame(OVCP)
OVCP



```

Question_2: Compute CI
-----
Using CI(theta1-theta2) and BCa
---
```{r CI(theta1-theta2), echo=F}
#######Bootstrapping############
#####Call the function########
MyBootstrapArray<-function(x, time, FUN='mean'){
  is.array(x)
  n<-length(x)
  BootFUN<-c()
  
  if(FUN=='mean'){
    for(i in 1:time-1){ 
      #bootstrap needs to include the original data
      rlist<-ceiling(runif(n, min=0, max=n))
      Bootlist<-x[rlist]
      BootFUN[i]<-mean(Bootlist)
    }
    BootFUN[time]<-mean(x)
    return(BootFUN)
  }else if(FUN=='median'){
    for(i in 1:time-1){
      rlist<-ceiling(runif(n, min=0, max=n))
      Bootlist<-x[rlist]
      BootFUN[i]<-median(Bootlist)
    }
    BootFUN[time]<-median(x)
    return(BootFUN)
  }
}


############################

ov<-OVCP$OV
cp<-OVCP$CP

ovBT<-MyBootstrapArray(ov, 1000)
cpBT<-MyBootstrapArray(cp, 1000)

ovcpDiff<-ovBT-cpBT
ovcpDiff.sort<-sort(ovcpDiff)
hist(ovcpDiff.sort, breaks=100,
     main=expression(paste(theta,'1-',
                theta,'2')),
     las=1, xlab='differences of the mean')
########Start BCa##############
ovcpJKdiff<-c()
for(i in 1:34){
  ovcpJKdiff[i]<-mean(ov[-i])-mean(cp[-i])
}
ovcpJKmean<-mean(ovcpJKdiff)
ovcpUpper<-sum((ovcpJKmean-ovcpDiff)^3)
ovcpLower<-6*sum((ovcpJKmean-ovcpDiff)^2)^(3/2)
ovcp.a<-ovcpUpper/ovcpLower
#G(theta)
ovcp.Gtheta<-myECDF(ovcpDiff.sort, 
                    mean(ovcpDiff.sort))
#Z0
ovcp.Z0<-myPercentile(Gauss, ovcp.Gtheta)

ovcp.Z1<-ovcp.Z0+(ovcp.Z0-1.96)/(1-ovcp.a*(ovcp.Z0-1.96))
ovcp.Z2<-ovcp.Z0+(ovcp.Z0+1.96)/(1-ovcp.a*(ovcp.Z0+1.96))
ovcp.prob1<-myECDF(Gauss, ovcp.Z1)
ovcp.prob2<-myECDF(Gauss, ovcp.Z2)
ovcp.CI<-myPercentile(ovcpDiff.sort, c(ovcp.prob1,
                              ovcp.prob2))

paste('CI of differences of mean falls between',
      ovcp.CI[1], 'and',
      ovcp.CI[2])
paste('0 is included in this CI, no significant difference between the two species')


```